version: '3.9'

services:
  flake8-installer:
    image: python:alpine3.17
    command: sh -c "apk add --no-cache gcc musl-dev && pip install flake8"
    volumes:
      - ./app:/app
    environment:
      - DEV=true
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
